<?php

define('SYNC_FROM_FILES_URL', variable_get('image_sync_from_url', ''));

function image_sync_menu() {
  $items = array();

  $items['sites/default/files'] = array(
    'title' => 'Files',
    'page callback' => 'image_sync_deliver',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );

  $items['admin/config/media/image_sync'] = array(
    'title' => t('Image sync settings'),
    'page callback'   => 'drupal_get_form',
    'page arguments' => array('image_sync_config_form'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

function image_sync_page_alter(&$vars){
  if(SYNC_FROM_FILES_URL == '' && user_access('access administration pages')){
      $message = t('You must set the remote files url for image_sync to start work! !link', array('!link' => l('Visit the settings page', 'admin/config/media/image_sync')));
      drupal_set_message($message);
  }
}

function image_sync_menu_alter(&$items){
  $directory_path = file_stream_wrapper_get_instance_by_scheme('public')->getDirectoryPath();
  $items[$directory_path . '/styles/%image_style']['page callback'] = 'image_sync_style_deliver';
}

function image_sync_deliver(){

$args = func_get_args();
$target = implode('/', $args);

  $image_uri = _image_sync_copy_image($target);

   if(is_file($image_uri)){
      $image = image_load($image_uri);
      file_transfer($image->source, array('Content-Type' => $image->info['mime_type'], 'Content-Length' => $image->info['file_size']));
   }


  drupal_exit();
}

function image_sync_style_deliver($style, $scheme) {
  // Check that the style is defined and the scheme is valid.
  if (!$style || !file_stream_wrapper_valid_scheme($scheme)) {
    drupal_exit();
  }

  $args = func_get_args();
  $all_arguments = $args;

  array_shift($args);
  array_shift($args);

  $target = implode('/', $args);

  _image_sync_copy_image($target);

  call_user_func_array('image_style_deliver', $all_arguments);
}

function _image_sync_copy_image($target){

  if(SYNC_FROM_FILES_URL !== ''){

    $path = file_build_uri($target);
    if(!is_file($path)){
      if(variable_get('image_sync_basic_auth', FALSE)){
        $username = variable_get('image_sync_basic_auth_user','');
        $pass = variable_get('image_sync_basic_auth_pass','');

        $context = stream_context_create(array(
            'http' => array('header'  => "Authorization: Basic " . base64_encode("$username:$pass"))
        ));
      }
      
      $dir_name = drupal_dirname($path);
      file_prepare_directory($dir_name, FILE_CREATE_DIRECTORY);
      
      if($content = @file_get_contents(SYNC_FROM_FILES_URL . '/' . $target, false, $context)){
        //Store in the filesystem.
        file_unmanaged_save_data($content, $path, FILE_EXISTS_REPLACE);
      }
      else{
        $image = @imagecreate(980, 490) or die("Cannot Initialize new GD image stream");
        $background_color = imagecolorallocate($image, 207, 239, 247);	
	      $save_path = file_stream_wrapper_get_instance_by_scheme('public')->getDirectoryPath() . '/' . $target;
	
        imagepng($image, $save_path);
        imagedestroy($image);
       }
    }
    return $path;
  }
}


function image_sync_config_form($form, &$form_state){

  $form = array();

  $form['image_sync_from_url'] = array(
    '#type' => 'textfield',
    '#default_value' => variable_get('image_sync_from_url', ''),
    '#title' => 'Remote private files url',
    '#description' => t('The absolute url to the sites files folder from where you want to download images. e.g. http://www.myproductionsite.se/sites/default/files'),
  );

   $form['image_sync_basic_auth'] = array(
    '#type' => 'checkbox',
    '#default_value' => variable_get('image_sync_basic_auth', FALSE),
    '#title' => 'Basic Authorization',
  );

   $form['image_sync_basic_auth_user'] = array(
    '#type' => 'textfield',
    '#default_value' => variable_get('image_sync_basic_auth_user', ''),
    '#title' => 'Basic Authorization username',
  );

   $form['image_sync_basic_auth_pass'] = array(
    '#type' => 'textfield',
    '#default_value' => variable_get('image_sync_basic_auth_pass', ''),
    '#title' => 'Basic Authorization password',
  );

  return system_settings_form($form);

}
